name: ci-only

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Local build
        id: local_build
        uses: docker/build-push-action@v2
        with:
          outputs: "type=docker,push=false"
          platforms: linux/amd64
          build-args: |
            Version=dev
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/inlets-connect:${{ github.sha }}
