---
apiVersion: v1
kind: Service
metadata:
  name: inlets-server
  namespace: inlets
  labels:
    app: inlets-server
spec:
  type: LoadBalancer
  ports:
    - name: inlets-control
      port: 8123
      protocol: TCP
      targetPort: 8123
      nodePort: 30000
    - name: inlets-connect
      port: 3128
      protocol: TCP
      targetPort: 3128
      nodePort: 30001
  selector:
    app: inlets-server
